project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "slide/**/*.qmd"
    - "!extern/**"
  resources:
    - slide/assets/pkg/**
    - slide/assets/julia-language.js

website:
  title: "Let’s run Julia everywhere"
  navbar:
    left:
      - href: slide/slide.qmd
        text: slide

format:
  html:
    theme: cosmo
    css: styles/style.css
    toc: true
